media:
  input: assets/img
  output: /assets/img

content:
  # Blog posts collection
  - name: posts
    label: Posts
    type: collection
    path: _posts
    format: yaml-frontmatter
    view:
      fields: [ title, date ]
    fields:
      - { label: Title, name: title, type: string }
      - { label: Subtitle, name: subtitle, type: string, required: false }
      - { label: Date, name: date, type: date }
      - { label: Image, name: image, type: image }
      - { label: Category, name: category, type: string }
      - { label: Author, name: author, type: string }
      - { label: Body, name: body, type: rich-text }

